GitHub home
araya-mentorship/desafio-githubapi-frontend pull request #6
Opened 2022-08-02 01:39 UTC by ketrynsdm

# Validação de PR

Criando a estrutura do front.

2022-08-02 15:44 UTC, eduardoaraya commented
Existem 2 arquivos de ícone, definir qual será utilizado e excluir o outro do repositório.

2022-08-02 15:45 UTC, eduardoaraya requested changes

2022-08-02 15:45 UTC, eduardoaraya commented on githubapi-frontend/src/app/app.component.spec.ts
> +  // });
Teste comentado, pf validar este teste

2022-08-02 15:45 UTC, eduardoaraya commented on githubapi-frontend/src/app/app.module.ts
> +    CUSTOM_ELEMENTS_SCHEMA
Pq a necessidade de usar o `CUSOM_ELEMENTS_SCHEMA` ? Remover-lo e declarar o componente corretamente no seu módulo.

2022-08-02 15:45 UTC, eduardoaraya commented on githubapi-frontend/src/app/shared/page/home/home.component.scss
> +
Remover linha em branco

2022-08-02 15:45 UTC, eduardoaraya commented on githubapi-frontend/src/app/shared/page/home/home.component.scss
> +.github{
Adicionar espaço: `.github {`

2022-08-02 15:45 UTC, eduardoaraya commented on githubapi-frontend/src/app/shared/page/home/home.component.ts
> +  description = 'logo'
A necessidade da descrição do logo estar em uma variável ?

2022-08-02 15:45 UTC, eduardoaraya commented on githubapi-frontend/src/app/shared/page/home/home.component.ts
> +  @Input() githubIcon = 'assets/git.svg'
A necessidade de passar o caminho do ícone por um `@Input` ?

2022-08-02 15:45 UTC, eduardoaraya commented on githubapi-frontend/src/app/shared/page/home/home.component.ts
> +  @Output() public search = new EventEmitter<void>()
Aonde será feita essa chamada do `@Output`, você pretende chama-lo em qual momento ? Pq a tipagem é `void` ?

2022-08-02 15:45 UTC, eduardoaraya commented on githubapi-frontend/src/app/shared/page/home/home.component.ts
> +
Remover linhas em branco

2022-08-02 15:45 UTC, eduardoaraya commented on githubapi-frontend/src/app/shared/search-users/search-users.component.html
> +
Remover linha em branco

2022-08-02 15:45 UTC, eduardoaraya commented on githubapi-frontend/src/app/shared/search-users/search-users.component.ts
> +
Remover linhas em branco do documento.

2022-08-02 15:45 UTC, eduardoaraya commented on githubapi-frontend/src/app/shared/search-users/search-users.component.ts
> +  @Output() public search = new EventEmitter<void>()
Acredito que este `Output` está correto, porém ele está tipado como `void`, qual seria o sentido desse tipo ? 
Se vc pretende emitir o valor que está pesquisando deveria ser tipado como `string` certo ?

2022-08-02 15:45 UTC, eduardoaraya commented on githubapi-frontend/src/app/shared/shared.module.ts
> +
Remover linhas em branco adicionais

2022-08-02 15:45 UTC, eduardoaraya commented on githubapi-frontend/src/index.html
> +  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous
Remover script js do bootstrap. Você não irá utiliza-lo. Apenas manter o import do css do bootstrap

2022-08-02 15:45 UTC, eduardoaraya commented on githubapi-frontend/src/app/shared/page/home/home.component.html
> +
Remover linha em branco

2022-08-02 15:45 UTC, eduardoaraya commented on githubapi-frontend/src/app/shared/listar-cards/listar-cards.component.ts
> +
Remover linhas em branco

2022-08-02 15:45 UTC, eduardoaraya commented on githubapi-frontend/src/app/shared/listar-cards/listar-cards.component.scss
> +.row{
Adicionar espaçamento entre `.row` e as chaves `{`

2022-08-04 15:01 UTC, ketrynsdm commented on githubapi-frontend/src/app/shared/page/home/home.component.ts
> +  @Input() githubIcon = 'assets/git.svg'
No projeto da DBmentora tinha chamado assim, mas removi pq a imagem não está aparecendo.

2022-08-04 15:06 UTC, ketrynsdm commented on githubapi-frontend/src/app/shared/page/home/home.component.ts
> +  @Output() public search = new EventEmitter<void>()
A chamada vai ser feita na lista-cards, o void que pq estava vendo a video aula e deixei lá, para retorna a logica depois

2022-08-04 15:10 UTC, ketrynsdm commented on githubapi-frontend/src/app/shared/page/home/home.component.ts
> +
removindo

2022-08-05 00:54 UTC, eduardoaraya approved these changes

2022-08-05 00:55 UTC, merged